[package]
name = "Tinge"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true
#opt-level = "z"  # Optimize for size.
#lto = true
#panic = "abort"

[dependencies]
wgpu = "28.0.0"
winit = "0.30.12"
pollster = "0.4"

env_logger = "0.11.8"
log = "0.4.29"

egui = "0.33.0"
egui-wgpu = "0.33.0"
egui-winit = "0.33.0"
wasm-bindgen = "0.2.108"
bytemuck = "1.24.0"
cfg-if = "1.0.3"
web-sys = "0.3.81"
anyhow = "1.0.100"
wasm-bindgen-futures = "0.4.58"

glam = "0.31.0"

image = "0.25.9"